# Generated by Django 3.2.10 on 2022-01-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfferApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='DepartmentId',
            new_name='CategoryId',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='DepartmentName',
            new_name='CategoryName',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Department',
            new_name='Category',
        ),
    ]
