# Generated by Django 3.2.10 on 2022-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfferApp', '0003_categories_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('OfferId', models.AutoField(primary_key=True, serialize=False)),
                ('OfferTitle', models.CharField(max_length=100)),
                ('OfferDescription', models.CharField(max_length=100)),
                ('OfferPrice', models.CharField(max_length=100)),
                ('OfferCreated', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AlterField(
            model_name='categories',
            name='Ordering',
            field=models.CharField(max_length=100),
        ),
    ]
